### ISSUE TITLE
Compile Errors Preview 9

### ISSUE THREAD

**Issue by codyvogt** [IvanJosipovic/BlazorFileSaver#1]
I'm getting the following errors on "CreateHostBuilder(args).Build().Run();" when I try to compile a Blazor server-side app.

System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: BlazorFileSaver.IBlazorFileSaver Lifetime: Singleton ImplementationType: BlazorFileSaver.BlazorFileSaverJS': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'BlazorFileSaver.IBlazorFileSaver'.)'

InvalidOperationException: Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'BlazorFileSaver.IBlazorFileSaver'.

**Comment by IvanJosipovic** [comment]
I'll look into this shortly, looks to be a simple fix.

**Comment by IvanJosipovic** [comment]
I just pushed version "3.0.0-preview9.19424.4-3".

Can you give it a try?

Code change: https://github.com/IvanJosipovic/BlazorFileSaver/commit/05cd70b07edada4d1d7adbc2d8e21a1678b7119e

**Comment by codyvogt** [comment]
Looks to be fixed, thanks!
